[feat] Convert Request Verification to Middleware
bandprotocol/pds-gateway pull request #28
Opened 2023-09-15 11:03 UTC by warittornc

## Description
Change request verification depend() to middleware to allow for more ordering flexibility

2023-09-19 06:37 UTC, taobun requested changes

2023-09-19 10:27 UTC, taobun commented on app/middleware/verify_request.py
> +                # Attempt to parse response from verify endpoint, if not possible, raise error and save report
Should we change comment to raise error? and then we add comment on finally instead?

2023-09-19 10:27 UTC, taobun commented on app/middleware/verify_request.py
> +                # If request is not delayed, return response from request
Add TODO: handle `is_delay` because now we haven't checked on this field yet

2023-09-19 10:27 UTC, taobun commented on tests/test_helper.py
> -async def test_verify_request_from_bandchain_success(httpx_mock: HTTPXMock):
Can we possible write this test for middleware?

2023-09-20 07:43 UTC, RogerKSI submitted a review, later dismissed

2023-09-20 07:48 UTC, RogerKSI submitted a review, later dismissed

2023-09-20 08:03 UTC, RogerKSI approved these changes

2023-09-20 08:25 UTC, taobun approved these changes

2023-09-20 08:26 UTC, merged